### ISSUE TITLE
convert it to marp-vscode-documents

### ISSUE THREAD

**Issue by alanlivio** [Octobug/marp-vscode-resume#1]
Hi @Octobug. 

First, congrats on the extension. I just wanted to say that it is well done. 👏🏻

Second, I suggest you convert it to marp-vscode-documents (and maybe a `theme: document`). I say this because people may want to use it for another use than just a resume.
For instance, I am a lecturer, and I like to use marp for slides, but I will also love to do some documents using marp examples (e.g. tutorial, guides).

If you do that and publish in the vscode marketplace, I bet you have a lot of potential users, me included 🙂.

I wish you the best.

**Comment by Octobug** [comment]
@alanlivio Thank you for your feedback!

But first of all, it is not an extension for VS Code ;)

I simply made it as a demo, to show people that a resume could be written in such way.

Your idea is great by the way!
